
            type owl__Thing {
                uri: ID! 
            }            
            
            type w3_ns_oa__TimeState @node(additionalLabels: ["w3_ns_oa__State"]){
                uri: ID! 
            }            
            
            type w3_ns_oa__Annotation {
                uri: ID! 
            }            
            
            type w3_ns_oa__SpecificResource @node(additionalLabels: ["w3_ns_oa__ResourceSelection"]){
                uri: ID! 
            }            
            
            type w3_ns_oa__ResourceSelection {
                uri: ID! 
            }            
            
            type w3_ns_oa__RangeSelector @node(additionalLabels: ["w3_ns_oa__Selector"]){
                uri: ID! 
            }            
            
            type rdfs__Resource {
                uri: ID! 
            }            
            
            type skos__Concept {
                uri: ID! 
            }            
            
            type w3_ns_activitystreams__OrderedCollection {
                uri: ID! 
            }            
            
            type w3_ns_oa__Choice @node(additionalLabels: ["w3_ns_activitystreams__OrderedCollection"]){
                uri: ID! 
            }            
            
            type w3_ns_oa__CssSelector @node(additionalLabels: ["w3_ns_oa__Selector"]){
                uri: ID! 
            }            
            
            type w3_ns_oa__CssStyle @node(additionalLabels: ["w3_ns_oa__Style"]){
                uri: ID! 
            }            
            
            type w3_ns_oa__DataPositionSelector @node(additionalLabels: ["w3_ns_oa__Selector"]){
                uri: ID! 
            }            
            
            type w3_ns_oa__Direction {
                uri: ID! 
            }            
            
            type w3_ns_oa__FragmentSelector @node(additionalLabels: ["w3_ns_oa__Selector"]){
                uri: ID! 
            }            
            
            type w3_ns_oa__HttpRequestState @node(additionalLabels: ["w3_ns_oa__State"]){
                uri: ID! 
            }            
            
            type w3_ns_oa__Motivation @node(additionalLabels: ["skos__Concept"]){
                uri: ID! 
            }            
            
            type w3_ns_oa__Selector {
                uri: ID! 
            }            
            
            type w3_ns_oa__State {
                uri: ID! 
            }            
            
            type w3_ns_oa__Style {
                uri: ID! 
            }            
            
            type w3_ns_oa__SvgSelector @node(additionalLabels: ["w3_ns_oa__Selector"]){
                uri: ID! 
            }            
            
            type w3_ns_oa__TextPositionSelector @node(additionalLabels: ["w3_ns_oa__Selector"]){
                uri: ID! 
            }            
            
            type w3_ns_oa__TextQuoteSelector @node(additionalLabels: ["w3_ns_oa__Selector"]){
                uri: ID! 
            }            
            
            type w3_ns_oa__TextualBody {
                uri: ID! 
            }            
            
            type w3_ns_oa__XPathSelector @node(additionalLabels: ["w3_ns_oa__Selector"]){
                uri: ID! 
            }            
            
            type foaf__Person @node(additionalLabels: ["foaf__Agent","http://www.w3.org/2003/01/geo/wgs84_pos#__SpatialThing"]){
                uri: ID! 
            }            
            
            type oeev__Association @node(additionalLabels: ["oeev__FacilityManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__AssociationWithScientificObject @node(additionalLabels: ["oeev__Association","oeev__FacilityManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__AssociationWithSensingDevice @node(additionalLabels: ["oeev__Association","oeev__FacilityManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Event {
                uri: ID! 
            }            
            
            type oeev__PestAttack @node(additionalLabels: ["oeev__Incident","oeev__Trouble","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__AddingProduct @node(additionalLabels: ["oeev__ScientificObjectManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__AutomaticCalibration @node(additionalLabels: ["oeev__Calibration","oeev__FacilityManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Breakdown @node(additionalLabels: ["oeev__Trouble","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Calibration @node(additionalLabels: ["oeev__FacilityManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Checking @node(additionalLabels: ["oeev__Servicing","oeev__Operability","oeev__FacilityManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Cleaning @node(additionalLabels: ["oeev__Servicing","oeev__Operability","oeev__FacilityManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Clipping @node(additionalLabels: ["oeev__ScientificObjectManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__CorrectiveMaintenance @node(additionalLabels: ["oeev__Operability","oeev__FacilityManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__CurativeTreatment @node(additionalLabels: ["oeev__Treatment","oeev__ScientificObjectManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Detasseling @node(additionalLabels: ["oeev__ScientificObjectManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Dysfunction @node(additionalLabels: ["oeev__Trouble","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__EvolutiveMaintenance @node(additionalLabels: ["oeev__Operability","oeev__FacilityManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__FacilityManagement @node(additionalLabels: ["oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Fertilization @node(additionalLabels: ["oeev__AddingProduct","oeev__ScientificObjectManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Harvesting @node(additionalLabels: ["oeev__ScientificObjectManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Incident @node(additionalLabels: ["oeev__Trouble","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Installation @node(additionalLabels: ["oeev__FacilityManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Irrigation @node(additionalLabels: ["oeev__ScientificObjectManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Loading @node(additionalLabels: ["oeev__ScientificObjectManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Lodging @node(additionalLabels: ["oeev__Incident","oeev__Trouble","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__ManualCalibration @node(additionalLabels: ["oeev__Calibration","oeev__FacilityManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Move @node(additionalLabels: ["oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Operability @node(additionalLabels: ["oeev__FacilityManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Pest {
                uri: ID! 
            }            
            
            type oeev__Flooding @node(additionalLabels: ["oeev__Incident","oeev__Trouble","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__PhenologyScoring @node(additionalLabels: ["oeev__ScientificObjectManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__PotFall @node(additionalLabels: ["oeev__Incident","oeev__Trouble","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Potting @node(additionalLabels: ["oeev__ScientificObjectManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__PreventativeTreatment @node(additionalLabels: ["oeev__Treatment","oeev__ScientificObjectManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Reparation @node(additionalLabels: ["oeev__CorrectiveMaintenance","oeev__Operability","oeev__FacilityManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Restart @node(additionalLabels: ["oeev__FacilityManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Sampling @node(additionalLabels: ["oeev__ScientificObjectManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__ScientificObjectManagement @node(additionalLabels: ["oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Servicing @node(additionalLabels: ["oeev__Operability","oeev__FacilityManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Sowing @node(additionalLabels: ["oeev__ScientificObjectManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Staking @node(additionalLabels: ["oeev__ScientificObjectManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Start @node(additionalLabels: ["oeev__FacilityManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Stop @node(additionalLabels: ["oeev__FacilityManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__StuckPlant @node(additionalLabels: ["oeev__Incident","oeev__Trouble","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Thinning @node(additionalLabels: ["oeev__ScientificObjectManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Treatment @node(additionalLabels: ["oeev__ScientificObjectManagement","oeev__Event"]){
                uri: ID! 
            }            
            
            type oeev__Trouble @node(additionalLabels: ["oeev__Event"]){
                uri: ID! 
            }            
            
            type oeso__Germplasm {
                uri: ID! 
            }            
            
            type oeso__Variable @node(additionalLabels: ["oeso__VariableBase"]){
                uri: ID! 
            }            
            
            type oeso__ScientificObject {
                uri: ID! 
            }            
            
            type oeso__Experiment {
                uri: ID! 
            }            
            
            type foaf__Organization @node(additionalLabels: ["foaf__Agent","oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type oeso__SensingDevice @node(additionalLabels: ["oeso__Device","oeso__Equipement","oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type oeso__Unit @node(additionalLabels: ["oeso__VariableBase"]){
                uri: ID! 
            }            
            
            type oeso__Project @node(additionalLabels: ["oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type w3_ns_prov__Activity {
                uri: ID! 
            }            
            
            type http://www.opensilex.org/security#__Group {
                uri: ID! 
            }            
            
            type opensilex_security__GroupUserProfile {
                uri: ID! 
            }            
            
            type opensilex_security__Profile {
                uri: ID! 
            }            
            
            type oeso__Actuator @node(additionalLabels: ["oeso__Device","oeso__Equipement","oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type oeso__AdministrativeDocument @node(additionalLabels: ["oeso__Document"]){
                uri: ID! 
            }            
            
            type oeso__Archive @node(additionalLabels: ["oeso__Datafile"]){
                uri: ID! 
            }            
            
            type oeso__Area @node(additionalLabels: ["oeso__Equipement","oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type oeso__Characteristic @node(additionalLabels: ["oeso__VariableBase"]){
                uri: ID! 
            }            
            
            type oeso__ClayeyArea @node(additionalLabels: ["oeso__SoilArea","oeso__StructuralArea","oeso__Area","oeso__Equipement","oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type oeso__Compartment @node(additionalLabels: ["oeso__Facility"]){
                uri: ID! 
            }            
            
            type oeso__Computation @node(additionalLabels: ["w3_ns_prov__Activity"]){
                uri: ID! 
            }            
            
            type oeso__ControlLaw @node(additionalLabels: ["oeso__Device","oeso__Equipement","oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type oeso__Datafile {
                uri: ID! 
            }            
            
            type oeso__Dataset @node(additionalLabels: ["oeso__Document"]){
                uri: ID! 
            }            
            
            type oeso__Device @node(additionalLabels: ["oeso__Equipement","oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type oeso__Document {
                uri: ID! 
            }            
            
            type oeso__ElaboratedVariable @node(additionalLabels: ["oeso__Variable","oeso__VariableBase"]){
                uri: ID! 
            }            
            
            type oeso__Entity @node(additionalLabels: ["oeso__VariableBase"]){
                uri: ID! 
            }            
            
            type oeso__EntityOfInterest @node(additionalLabels: ["oeso__VariableBase"]){
                uri: ID! 
            }            
            
            type oeso__Equipement @node(additionalLabels: ["oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type oeso__ExperimentalCondition {
                uri: ID! 
            }            
            
            type oeso__ExperimentalProtocol @node(additionalLabels: ["oeso__TechnicalDocument","oeso__Document"]){
                uri: ID! 
            }            
            
            type oeso__ExperimentalUnit @node(additionalLabels: ["foaf__Organization","foaf__Agent","oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type oeso__Facility {
                uri: ID! 
            }            
            
            type oeso__Factor @node(additionalLabels: ["oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type oeso__FactorLevel @node(additionalLabels: ["oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type oeso__FloodableArea @node(additionalLabels: ["oeso__StructuralArea","oeso__Area","oeso__Equipement","oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type oeso__ITKDocument @node(additionalLabels: ["oeso__TechnicalDocument","oeso__Document"]){
                uri: ID! 
            }            
            
            type oeso__Image @node(additionalLabels: ["oeso__Datafile"]){
                uri: ID! 
            }            
            
            type oeso__ImageAcquisition @node(additionalLabels: ["w3_ns_prov__Activity"]){
                uri: ID! 
            }            
            
            type oeso__ImageAnalysis @node(additionalLabels: ["w3_ns_prov__Activity"]){
                uri: ID! 
            }            
            
            type oeso__Installation @node(additionalLabels: ["foaf__Organization","foaf__Agent","oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type oeso__InteractiveResource @node(additionalLabels: ["oeso__Document"]){
                uri: ID! 
            }            
            
            type oeso__LimestoneArea @node(additionalLabels: ["oeso__SoilArea","oeso__StructuralArea","oeso__Area","oeso__Equipement","oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type oeso__MeasuresAcquisition @node(additionalLabels: ["w3_ns_prov__Activity"]){
                uri: ID! 
            }            
            
            type oeso__Method @node(additionalLabels: ["oeso__VariableBase"]){
                uri: ID! 
            }            
            
            type oeso__Multimedia @node(additionalLabels: ["oeso__Document"]){
                uri: ID! 
            }            
            
            type oeso__Operator @node(additionalLabels: ["foaf__Agent"]){
                uri: ID! 
            }            
            
            type oeso__Population @node(additionalLabels: ["oeso__ScientificObject"]){
                uri: ID! 
            }            
            
            type oeso__Provenance {
                uri: ID! 
            }            
            
            type oeso__Publication @node(additionalLabels: ["oeso__ScientificDocument","oeso__Document"]){
                uri: ID! 
            }            
            
            type oeso__RGBImage @node(additionalLabels: ["oeso__Image","oeso__Datafile"]){
                uri: ID! 
            }            
            
            type oeso__Report @node(additionalLabels: ["oeso__ScientificDocument","oeso__Document"]){
                uri: ID! 
            }            
            
            type oeso__ResearchUnit @node(additionalLabels: ["foaf__Organization","foaf__Agent","oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type oeso__Sample @node(additionalLabels: ["oeso__ScientificObject"]){
                uri: ID! 
            }            
            
            type oeso__ScientificDocument @node(additionalLabels: ["oeso__Document"]){
                uri: ID! 
            }            
            
            type oeso__Shed @node(additionalLabels: ["oeso__Equipement","oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type oeso__ShinyAppPackage @node(additionalLabels: ["oeso__InteractiveResource","oeso__Document"]){
                uri: ID! 
            }            
            
            type oeso__Software @node(additionalLabels: ["oeso__Device","oeso__Equipement","oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type oeso__SoilArea @node(additionalLabels: ["oeso__StructuralArea","oeso__Area","oeso__Equipement","oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type oeso__Species @node(additionalLabels: ["oeso__Germplasm"]){
                uri: ID! 
            }            
            
            type oeso__Station @node(additionalLabels: ["oeso__Device","oeso__Equipement","oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type oeso__StructuralArea @node(additionalLabels: ["oeso__Area","oeso__Equipement","oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type oeso__TechnicalDocument @node(additionalLabels: ["oeso__Document"]){
                uri: ID! 
            }            
            
            type oeso__TemporalArea @node(additionalLabels: ["oeso__Area","oeso__Equipement","oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type oeso__Trait {
                uri: ID! 
            }            
            
            type oeso__Treatment @node(additionalLabels: ["oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type oeso__VariableBase {
                uri: ID! 
            }            
            
            type oeso__VariablesGroup @node(additionalLabels: ["ns__Bag"]){
                uri: ID! 
            }            
            
            type oeso__Vector @node(additionalLabels: ["oeso__Device","oeso__Equipement","oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type oeso__WebSite @node(additionalLabels: ["oeso__InteractiveResource","oeso__Document"]){
                uri: ID! 
            }            
            
            type oeso__WindyArea @node(additionalLabels: ["oeso__StructuralArea","oeso__Area","oeso__Equipement","oeso__ExperimentalCondition"]){
                uri: ID! 
            }            
            
            type ns__Bag {
                uri: ID! 
            }            
            
            type sinfonia__Wine @node(additionalLabels: ["oeso__ScientificObject"]){
                uri: ID! 
            }            
            
            type sinfonia__ExperimentalField @node(additionalLabels: ["oeso__InfrastructureFacility"]){
                uri: ID! 
            }            
            
            type sinfonia__Subplot @node(additionalLabels: ["oeso__ScientificObject"]){
                uri: ID! 
            }            
            
            type sinfonia__Cellar @node(additionalLabels: ["oeso__InfrastructureFacility"]){
                uri: ID! 
            }            
            
            type sinfonia__DMP @node(additionalLabels: ["oeso__Document"]){
                uri: ID! 
            }            
            
            type sinfonia__Laboratory @node(additionalLabels: ["oeso__InfrastructureFacility"]){
                uri: ID! 
            }            
            
            type sinfonia__LocalInfrastructure @node(additionalLabels: ["oeso__Infrastructure"]){
                uri: ID! 
            }            
            
            type sinfonia__NationalInfrastructure @node(additionalLabels: ["oeso__Infrastructure"]){
                uri: ID! 
            }            
            
            type sinfonia__POM @node(additionalLabels: ["oeso__SoftSensor"]){
                uri: ID! 
            }            
            
            type sinfonia__Plot @node(additionalLabels: ["oeso__ScientificObject"]){
                uri: ID! 
            }            
            
            type sinfonia__Sample @node(additionalLabels: ["oeso__ScientificObject"]){
                uri: ID! 
            }            
            
            type sinfonia__Soil @node(additionalLabels: ["oeso__ScientificObject"]){
                uri: ID! 
            }            
            
            type sinfonia__TastingRoom @node(additionalLabels: ["oeso__InfrastructureFacility"]){
                uri: ID! 
            }            
            
            type sinfonia__Vinestock @node(additionalLabels: ["oeso__ScientificObject"]){
                uri: ID! 
            }            
            
            type sinfonia__Vinification @node(additionalLabels: ["oeso__ScientificObject"]){
                uri: ID! 
            }            
            
            type sinfonia__Winery @node(additionalLabels: ["oeso__InfrastructureFacility"]){
                uri: ID! 
            }            
            
            type rdfs__Class {
                uri: ID! 
            }            
            
            type foaf__LabelProperty {
                uri: ID! 
            }            
            
            type foaf__Agent {
                uri: ID! 
            }            
            
            type http://www.w3.org/2003/01/geo/wgs84_pos#__SpatialThing {
                uri: ID! 
            }            
            
            type foaf__Document {
                uri: ID! 
            }            
            
            type foaf__Group @node(additionalLabels: ["foaf__Agent"]){
                uri: ID! 
            }            
            
            type foaf__Project {
                uri: ID! 
            }            
            
            type foaf__Image @node(additionalLabels: ["foaf__Document"]){
                uri: ID! 
            }            
            
            type foaf__PersonalProfileDocument @node(additionalLabels: ["foaf__Document"]){
                uri: ID! 
            }            
            
            type foaf__OnlineAccount @node(additionalLabels: ["owl__Thing"]){
                uri: ID! 
            }            
            
            type foaf__OnlineGamingAccount @node(additionalLabels: ["foaf__OnlineAccount","owl__Thing"]){
                uri: ID! 
            }            
            
            type foaf__OnlineEcommerceAccount @node(additionalLabels: ["foaf__OnlineAccount","owl__Thing"]){
                uri: ID! 
            }            
            
            type foaf__OnlineChatAccount @node(additionalLabels: ["foaf__OnlineAccount","owl__Thing"]){
                uri: ID! 
            }            
            
            type owl__DatatypeProperty {
                uri: ID! 
            }            
            
            type w3_ns_prov__Agent {
                uri: ID! 
            }            
            
            type w3_ns_prov__Entity {
                uri: ID! 
            }            
            
            type w3_ns_prov__Person @node(additionalLabels: ["w3_ns_prov__Agent"]){
                uri: ID! 
            }            
            
            type w3_ns_prov__SoftwareAgent @node(additionalLabels: ["w3_ns_prov__Agent"]){
                uri: ID! 
            }            
            